<?php

function cuba_common_configuration_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'node_cuba_ct_web_page_form' || 'node_cuba_ct_web_page_edit_form') {
    $form['#attached']['library'][] = 'cuba_theme/global-styling';
  }
}

/**
 * Implements hook_page_attachments().
 */
function cuba_common_configuration_page_attachments(array &$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $page['#attached']['library'][] = 'cuba_theme/admin-extras';
    return;
  }
}

/*
 * Implements hook_preprocess_html().
 */
function cuba_common_configuration_preprocess_html(&$variables) {

  // Get the current path.
  $current_path = \Drupal::service('path.current')->getPath();

  // Get the alias.
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Check if we are on a past and future conference page and add extra class.
  if ($path_alias == '/past-and-future-conferences' || $path_alias == '/conferences-precedentes-et-futures') {

    // Add extra class for styling.
    $variables['attributes']['class'][] = 'past-and-future';
  }
}
