<?php

function cuba_common_configuration_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'node_cuba_ct_web_page_form' || 'node_cuba_ct_web_page_edit_form') {
    $form['#attached']['library'][] = 'cuba_theme/global-styling';
  }
}

/**
 * Implements hook_page_attachments().
 */
function cuba_common_configuration_page_attachments(array &$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $page['#attached']['library'][] = 'cuba_theme/admin-extras';
    return;
  }
}

/*
 * Implements hook_preprocess_html().
 */
function cuba_common_configuration_preprocess_html(&$variables) {

  // Get the current path.
  $current_path = \Drupal::service('path.current')->getPath();

  // Get the alias.
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Check if we are on a past and future conference page and add extra class.
  if ($path_alias == '/past-and-future-conferences' || $path_alias == '/conferences-precedentes-et-futures') {

    // Add extra class for styling.
    $variables['attributes']['class'][] = 'past-and-future';
  }
}

/**
 * Implements hook_theme().
 */
function cuba_common_configuration_theme($existing, $type, $theme, $path) {
  return [
    'cuba_management_links' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_toolbar_alter().
 */
function cuba_common_configuration_toolbar_alter(&$items) {

  // Move the 'Dashboards' link at the left of the tooltar.
  $items['dashboards']['#weight'] = -15;

  // Rename 'Dashboards' to 'Workbench'.
  $items['dashboards']['tab']['#title'] = 'Workbench';

  // Get the current user.
  $current_user = \Drupal::currentUser();

  // Ensure that we are not user 1.
  if ($current_user->id() !== '1') {

    // Load in the roles.
    $roles = $current_user->getRoles();

    // As long as not an administrator, remove the Manage link from the toolbar.
    if (!in_array('administrator', $roles)) {

      // Remove the manage link.
      unset($items['administration']);
    }
  }
}

