<?php

/**
 * Implements hook_form_alter().
 */
function cuba_common_configuration_form_alter(&$form, &$form_state, $form_id) {

  // If we are on a web page node edit, then add global-stylings so that paragraphs are viewable.
  if ($form_id == 'node_cuba_ct_web_page_form' || 'node_cuba_ct_web_page_edit_form') {
    $form['#attached']['library'][] = 'cuba_theme/global-styling';
  }

  // If we are on a search form then unset the types of searches and languages.
  if ($form_id == 'search_form') {
    unset($form['advanced']['types-fieldset']);
    unset($form['advanced']['lang-fieldset']);
  }

  if ($form_id == 'node_cuba_ct_conference_section_form') {
    unset($form['langcode']);
  }
}

/**
 * Implements hook_page_attachments().
 */
function cuba_common_configuration_page_attachments(array &$page) {
  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $current_path = \Drupal::service('path.current')->getPath();
  if ($is_admin || $current_path == '/dashboard/cuba_my_dashboard') {
    $page['#attached']['library'][] = 'cuba_theme/admin-extras';
    return;
  }
}

/*
 * Implements hook_preprocess_html().
 */
function cuba_common_configuration_preprocess_html(&$variables) {

  // Get the current path.
  $current_path = \Drupal::service('path.current')->getPath();

  // Get the alias.
  $path_alias = \Drupal::service('path_alias.manager')->getAliasByPath($current_path);

  // Check if we are on a past and future conference page and add extra class.
  if ($path_alias == '/past-and-future-conferences' || $path_alias == '/conferences-precedentes-et-futures') {

    // Add extra class for styling.
    $variables['attributes']['class'][] = 'past-and-future';
  }

  $user_roles = \Drupal::currentUser()->getRoles();
  $allowed_roles = ['cuba_role_site_manager', 'cuba_role_content_editor'];

  foreach ($user_roles as $user_role) {
    if (in_array($user_role, $allowed_roles)) {
      $language =  \Drupal::languageManager()->getCurrentLanguage()->getName();
      if ($language == 'Francais') {
        $variables['attributes']['class'][] = 'french';
      }
      else if ($language == 'English') {
        $variables['attributes']['class'][] = 'english';
      }
    }
  }
  /*
  if ($user->id() == 1 && $language == 'Francais') {
    $variables['attributes']['class'][] = 'french';
  }
  */
}

/**
 * Implements hook_theme().
 */
function cuba_common_configuration_theme($existing, $type, $theme, $path) {
  return [
    'cuba_management_links' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
    'cuba_content_creation_links' => [
      'variables' => [
        'links' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_toolbar_alter().
 */
function cuba_common_configuration_toolbar_alter(&$items) {

  // Move the 'Dashboards' link at the left of the tooltar.
  $items['dashboards']['#weight'] = -15;

  // Rename 'Dashboards' to 'Workbench'.
  $items['dashboards']['tab']['#title'] = 'Workbench';

  // Get the current user.
  $current_user = \Drupal::currentUser();

  // Ensure that we are not user 1.
  if ($current_user->id() !== '1') {

    // Load in the roles.
    $roles = $current_user->getRoles();

    // As long as not an administrator, remove the Manage link from the toolbar.
    if (!in_array('administrator', $roles)) {

      // Remove the manage link.
      unset($items['administration']);
    }
  }
}

/**
 * Implements hook_query_search_node_search_alter().
 *
 * Ensure that the search is only in the users current language.
 */
function cuba_common_configuration_query_search_node_search_alter(&$query) {
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $query->condition('i.langcode', array($language, 'und', 'zxx'), 'IN');
}
