name: 'Cuba common configuration'
description: 'Common config for CUBA website'
type: module
core_version_requirement: ^9
dependencies:
  - better_exposed_filters
  - block
  - ckeditor
  - content_translation
  - ctools
  - cuba_ct_board_of_directors
  - cuba_ct_conference_section
  - cuba_ct_web_page
  - cuba_media
  - cuba_paragraphs
  - dashboards
  - editor
  - editor_file
  - file
  - filter
  - language
  - language_switcher_extended
  - media
  - menu_admin_per_menu
  - menu_link_content
  - node
  - redirect_after_login
  - role_delegation
  - sitemap
  - superfish
  - system
  - taxonomy
  - taxonomy_menu
  - twig_field_value
  - twig_tweak
  - user
  - views
  - views_bulk_operations
