name: 'Cuba common configuration'
description: 'Common config for CUBA website'
type: module
core_version_requirement: ^9
dependencies:
  - ckeditor
  - cuba_ct_conference_section
  - cuba_media
  - cuba_paragraphs
  - editor
  - filter
  - language
  - language_switcher_extended
  - media
